
export default {
    REQUEST_TO_GET_VIDEO_LIST: 'REQUEST_TO_GET_VIDEO_LIST',
    GET_VIDEO_LIST_SUCCESS: 'GET_VIDEO_LIST_SUCCESS',
    GET_VIDEO_LIST_ERROR: 'GET_VIDEO_LIST_ERROR',
    ADD_ERROR_MESSAGE: 'ADD_ERROR_MESSAGE',
    CLEAR_ERROR_MESSAGE: 'CLEAR_ERROR_MESSAGE',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
    SIGN_IN_REQUEST: 'SIGN_IN_REQUEST',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_IN_FAIL: 'SIGN_IN_FAIL'

}