
export default {
    VIDEO_BACKGROUND_COLOR: '#fafafa',
    THEME_COLOR: '#FFA25C',
    DASHBOARD_BACKGROUND_COLOR: '#F0F8FF',
    SPINNER_COLOR: 'blue',
    GRAY_BORDER: '#ccc',
    HEADING_COLOR: '#000',
    PROFILE_BACKGROUND_COLOR: '#fafafa'
}